/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AppUserResponseDto } from '../model';
// @ts-ignore
import type { CreateAppUserDto } from '../model';
/**
 * AppUsersSdkApi - axios parameter creator
 * @export
 */
export const AppUsersSdkApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new app user
         * @param {CreateAppUserDto} createAppUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAppUser: async (createAppUserDto: CreateAppUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAppUserDto' is not null or undefined
            assertParamExists('createAppUser', 'createAppUserDto', createAppUserDto)
            const localVarPath = `/sdk/app-users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAppUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppUsersSdkApi - functional programming interface
 * @export
 */
export const AppUsersSdkApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppUsersSdkApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new app user
         * @param {CreateAppUserDto} createAppUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAppUser(createAppUserDto: CreateAppUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppUserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAppUser(createAppUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppUsersSdkApi.createAppUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppUsersSdkApi - factory interface
 * @export
 */
export const AppUsersSdkApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppUsersSdkApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new app user
         * @param {CreateAppUserDto} createAppUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAppUser(createAppUserDto: CreateAppUserDto, options?: RawAxiosRequestConfig): AxiosPromise<AppUserResponseDto> {
            return localVarFp.createAppUser(createAppUserDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppUsersSdkApi - object-oriented interface
 * @export
 * @class AppUsersSdkApi
 * @extends {BaseAPI}
 */
export class AppUsersSdkApi extends BaseAPI {
    /**
     * 
     * @summary Create a new app user
     * @param {CreateAppUserDto} createAppUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppUsersSdkApi
     */
    public createAppUser(createAppUserDto: CreateAppUserDto, options?: RawAxiosRequestConfig) {
        return AppUsersSdkApiFp(this.configuration).createAppUser(createAppUserDto, options).then((request) => request(this.axios, this.basePath));
    }
}

