/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DeviceChangeResponseDto } from '../model';
// @ts-ignore
import type { DeviceChangeTimelineDto } from '../model';
/**
 * DeviceChangesApi - axios parameter creator
 * @export
 */
export const DeviceChangesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a summary of changes by table
         * @param {string} projectId Project ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetChangesByTable: async (projectId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('deviceChangesControllerGetChangesByTable', 'projectId', projectId)
            const localVarPath = `/projects/{projectId}/device-changes/summary`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single device change by ID
         * @param {string} projectId Project ID
         * @param {string} id Device change ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetDeviceChangeById: async (projectId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('deviceChangesControllerGetDeviceChangeById', 'projectId', projectId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deviceChangesControllerGetDeviceChangeById', 'id', id)
            const localVarPath = `/projects/{projectId}/device-changes/{id}`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get device changes with filtering and pagination
         * @param {string} projectId Project ID
         * @param {string} [tableName] Filter by table name
         * @param {string} [recordId] Filter by record ID
         * @param {string} [changeType] Filter by change type (CREATE, UPDATE, DELETE)
         * @param {string} [deviceId] Filter by device ID
         * @param {string} [userIdentifier] Filter by user identifier
         * @param {string} [startDate] Start date for filtering (ISO format)
         * @param {string} [endDate] End date for filtering (ISO format)
         * @param {number} [page] Page number for pagination
         * @param {number} [limit] Items per page for pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetDeviceChanges: async (projectId: string, tableName?: string, recordId?: string, changeType?: string, deviceId?: string, userIdentifier?: string, startDate?: string, endDate?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('deviceChangesControllerGetDeviceChanges', 'projectId', projectId)
            const localVarPath = `/projects/{projectId}/device-changes`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tableName !== undefined) {
                localVarQueryParameter['tableName'] = tableName;
            }

            if (recordId !== undefined) {
                localVarQueryParameter['recordId'] = recordId;
            }

            if (changeType !== undefined) {
                localVarQueryParameter['changeType'] = changeType;
            }

            if (deviceId !== undefined) {
                localVarQueryParameter['deviceId'] = deviceId;
            }

            if (userIdentifier !== undefined) {
                localVarQueryParameter['userIdentifier'] = userIdentifier;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get timeline of changes for a specific record
         * @param {string} projectId Project ID
         * @param {string} tableName Table name
         * @param {string} recordId Record ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetRecordTimeline: async (projectId: string, tableName: string, recordId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('deviceChangesControllerGetRecordTimeline', 'projectId', projectId)
            // verify required parameter 'tableName' is not null or undefined
            assertParamExists('deviceChangesControllerGetRecordTimeline', 'tableName', tableName)
            // verify required parameter 'recordId' is not null or undefined
            assertParamExists('deviceChangesControllerGetRecordTimeline', 'recordId', recordId)
            const localVarPath = `/projects/{projectId}/device-changes/tables/{tableName}/records/{recordId}/timeline`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"tableName"}}`, encodeURIComponent(String(tableName)))
                .replace(`{${"recordId"}}`, encodeURIComponent(String(recordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get unique table names from device changes
         * @param {string} projectId Project ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetTableNames: async (projectId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('deviceChangesControllerGetTableNames', 'projectId', projectId)
            const localVarPath = `/projects/{projectId}/device-changes/tables`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeviceChangesApi - functional programming interface
 * @export
 */
export const DeviceChangesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeviceChangesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a summary of changes by table
         * @param {string} projectId Project ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceChangesControllerGetChangesByTable(projectId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: number; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deviceChangesControllerGetChangesByTable(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceChangesApi.deviceChangesControllerGetChangesByTable']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single device change by ID
         * @param {string} projectId Project ID
         * @param {string} id Device change ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceChangesControllerGetDeviceChangeById(projectId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceChangeResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deviceChangesControllerGetDeviceChangeById(projectId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceChangesApi.deviceChangesControllerGetDeviceChangeById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get device changes with filtering and pagination
         * @param {string} projectId Project ID
         * @param {string} [tableName] Filter by table name
         * @param {string} [recordId] Filter by record ID
         * @param {string} [changeType] Filter by change type (CREATE, UPDATE, DELETE)
         * @param {string} [deviceId] Filter by device ID
         * @param {string} [userIdentifier] Filter by user identifier
         * @param {string} [startDate] Start date for filtering (ISO format)
         * @param {string} [endDate] End date for filtering (ISO format)
         * @param {number} [page] Page number for pagination
         * @param {number} [limit] Items per page for pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceChangesControllerGetDeviceChanges(projectId: string, tableName?: string, recordId?: string, changeType?: string, deviceId?: string, userIdentifier?: string, startDate?: string, endDate?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceChangeResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deviceChangesControllerGetDeviceChanges(projectId, tableName, recordId, changeType, deviceId, userIdentifier, startDate, endDate, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceChangesApi.deviceChangesControllerGetDeviceChanges']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get timeline of changes for a specific record
         * @param {string} projectId Project ID
         * @param {string} tableName Table name
         * @param {string} recordId Record ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceChangesControllerGetRecordTimeline(projectId: string, tableName: string, recordId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceChangeTimelineDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deviceChangesControllerGetRecordTimeline(projectId, tableName, recordId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceChangesApi.deviceChangesControllerGetRecordTimeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get unique table names from device changes
         * @param {string} projectId Project ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deviceChangesControllerGetTableNames(projectId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deviceChangesControllerGetTableNames(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceChangesApi.deviceChangesControllerGetTableNames']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeviceChangesApi - factory interface
 * @export
 */
export const DeviceChangesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeviceChangesApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a summary of changes by table
         * @param {string} projectId Project ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetChangesByTable(projectId: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: number; }> {
            return localVarFp.deviceChangesControllerGetChangesByTable(projectId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single device change by ID
         * @param {string} projectId Project ID
         * @param {string} id Device change ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetDeviceChangeById(projectId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<DeviceChangeResponseDto> {
            return localVarFp.deviceChangesControllerGetDeviceChangeById(projectId, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get device changes with filtering and pagination
         * @param {string} projectId Project ID
         * @param {string} [tableName] Filter by table name
         * @param {string} [recordId] Filter by record ID
         * @param {string} [changeType] Filter by change type (CREATE, UPDATE, DELETE)
         * @param {string} [deviceId] Filter by device ID
         * @param {string} [userIdentifier] Filter by user identifier
         * @param {string} [startDate] Start date for filtering (ISO format)
         * @param {string} [endDate] End date for filtering (ISO format)
         * @param {number} [page] Page number for pagination
         * @param {number} [limit] Items per page for pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetDeviceChanges(projectId: string, tableName?: string, recordId?: string, changeType?: string, deviceId?: string, userIdentifier?: string, startDate?: string, endDate?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<DeviceChangeResponseDto> {
            return localVarFp.deviceChangesControllerGetDeviceChanges(projectId, tableName, recordId, changeType, deviceId, userIdentifier, startDate, endDate, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get timeline of changes for a specific record
         * @param {string} projectId Project ID
         * @param {string} tableName Table name
         * @param {string} recordId Record ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetRecordTimeline(projectId: string, tableName: string, recordId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeviceChangeTimelineDto> {
            return localVarFp.deviceChangesControllerGetRecordTimeline(projectId, tableName, recordId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get unique table names from device changes
         * @param {string} projectId Project ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deviceChangesControllerGetTableNames(projectId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.deviceChangesControllerGetTableNames(projectId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeviceChangesApi - object-oriented interface
 * @export
 * @class DeviceChangesApi
 * @extends {BaseAPI}
 */
export class DeviceChangesApi extends BaseAPI {
    /**
     * 
     * @summary Get a summary of changes by table
     * @param {string} projectId Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceChangesApi
     */
    public deviceChangesControllerGetChangesByTable(projectId: string, options?: RawAxiosRequestConfig) {
        return DeviceChangesApiFp(this.configuration).deviceChangesControllerGetChangesByTable(projectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single device change by ID
     * @param {string} projectId Project ID
     * @param {string} id Device change ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceChangesApi
     */
    public deviceChangesControllerGetDeviceChangeById(projectId: string, id: string, options?: RawAxiosRequestConfig) {
        return DeviceChangesApiFp(this.configuration).deviceChangesControllerGetDeviceChangeById(projectId, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get device changes with filtering and pagination
     * @param {string} projectId Project ID
     * @param {string} [tableName] Filter by table name
     * @param {string} [recordId] Filter by record ID
     * @param {string} [changeType] Filter by change type (CREATE, UPDATE, DELETE)
     * @param {string} [deviceId] Filter by device ID
     * @param {string} [userIdentifier] Filter by user identifier
     * @param {string} [startDate] Start date for filtering (ISO format)
     * @param {string} [endDate] End date for filtering (ISO format)
     * @param {number} [page] Page number for pagination
     * @param {number} [limit] Items per page for pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceChangesApi
     */
    public deviceChangesControllerGetDeviceChanges(projectId: string, tableName?: string, recordId?: string, changeType?: string, deviceId?: string, userIdentifier?: string, startDate?: string, endDate?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return DeviceChangesApiFp(this.configuration).deviceChangesControllerGetDeviceChanges(projectId, tableName, recordId, changeType, deviceId, userIdentifier, startDate, endDate, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get timeline of changes for a specific record
     * @param {string} projectId Project ID
     * @param {string} tableName Table name
     * @param {string} recordId Record ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceChangesApi
     */
    public deviceChangesControllerGetRecordTimeline(projectId: string, tableName: string, recordId: string, options?: RawAxiosRequestConfig) {
        return DeviceChangesApiFp(this.configuration).deviceChangesControllerGetRecordTimeline(projectId, tableName, recordId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get unique table names from device changes
     * @param {string} projectId Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceChangesApi
     */
    public deviceChangesControllerGetTableNames(projectId: string, options?: RawAxiosRequestConfig) {
        return DeviceChangesApiFp(this.configuration).deviceChangesControllerGetTableNames(projectId, options).then((request) => request(this.axios, this.basePath));
    }
}

