/* tslint:disable */
/* eslint-disable */
/**
 * DeltaSync API
 * API documentation for DeltaSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserResponseDto } from './user-response-dto';

/**
 * 
 * @export
 * @interface AuthenticatedResponseDto
 */
export interface AuthenticatedResponseDto {
    /**
     * 
     * @type {UserResponseDto}
     * @memberof AuthenticatedResponseDto
     */
    'user': UserResponseDto;
    /**
     * JWT access token
     * @type {string}
     * @memberof AuthenticatedResponseDto
     */
    'accessToken': string;
    /**
     * JWT refresh token
     * @type {string}
     * @memberof AuthenticatedResponseDto
     */
    'refreshToken': string;
}

