/* tslint:disable */
/* eslint-disable */
/**
 * DeltaSync API
 * API documentation for DeltaSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthTokenResponseDto
 */
export interface AuthTokenResponseDto {
    /**
     * The unique identifier of the auth token
     * @type {string}
     * @memberof AuthTokenResponseDto
     */
    'id': string;
    /**
     * The ID of the project this token belongs to
     * @type {string}
     * @memberof AuthTokenResponseDto
     */
    'projectId': string;
    /**
     * The ID of the user who created this token
     * @type {string}
     * @memberof AuthTokenResponseDto
     */
    'userId': string;
    /**
     * The name of the auth token
     * @type {string}
     * @memberof AuthTokenResponseDto
     */
    'name': string;
}

