/* tslint:disable */
/* eslint-disable */
/**
 * DeltaSync API
 * API documentation for DeltaSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthTokenResponseDto } from './auth-token-response-dto';

/**
 * 
 * @export
 * @interface ProjectResponseDto
 */
export interface ProjectResponseDto {
    /**
     * The unique identifier of the project
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'id': string;
    /**
     * The name of the project
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'name': string;
    /**
     * The ID of the user who owns this project
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'userId': string;
    /**
     * Number of app users in this project
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'appUsersCount': number;
    /**
     * When the project was created
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'createdAt': string;
    /**
     * When the project was last updated
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'updatedAt': string;
    /**
     * When the project was deleted
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'userCount': number;
    /**
     * Auth tokens for the project
     * @type {Array<AuthTokenResponseDto>}
     * @memberof ProjectResponseDto
     */
    'authTokens': Array<AuthTokenResponseDto>;
}

