/* tslint:disable */
/* eslint-disable */
/**
 * DeltaSync API
 * API documentation for DeltaSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RefreshTokenDto
 */
export interface RefreshTokenDto {
    /**
     * The refresh token to exchange for a new access token
     * @type {string}
     * @memberof RefreshTokenDto
     */
    'refreshToken': string;
}

