/* tslint:disable */
/* eslint-disable */
/**
 * DeltaSync API
 * API documentation for DeltaSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * User first name
     * @type {string}
     * @memberof RegisterDto
     */
    'firstName': string;
    /**
     * User last name
     * @type {string}
     * @memberof RegisterDto
     */
    'lastName': string;
}

