/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppUserResponseDto
 */
export interface AppUserResponseDto {
    /**
     * Unique identifier of the app user
     * @type {string}
     * @memberof AppUserResponseDto
     */
    'userIdentifier': string;
    /**
     * ID of the project the user belongs to
     * @type {string}
     * @memberof AppUserResponseDto
     */
    'projectId': string;
    /**
     * Timestamp when the user was created
     * @type {string}
     * @memberof AppUserResponseDto
     */
    'createdAt': string;
    /**
     * List of devices associated with the user
     * @type {Array<object>}
     * @memberof AppUserResponseDto
     */
    'devices': Array<object>;
}

