/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeviceDto } from './device-dto';

/**
 * 
 * @export
 * @interface AppUserDto
 */
export interface AppUserDto {
    /**
     * Unique identifier for the app user
     * @type {string}
     * @memberof AppUserDto
     */
    'userIdentifier': string;
    /**
     * Project ID this user belongs to
     * @type {string}
     * @memberof AppUserDto
     */
    'projectId': string;
    /**
     * Devices associated with this user
     * @type {Array<DeviceDto>}
     * @memberof AppUserDto
     */
    'devices': Array<DeviceDto>;
    /**
     * When the user was created
     * @type {string}
     * @memberof AppUserDto
     */
    'createdAt': string;
    /**
     * When the user was deleted, if applicable
     * @type {object}
     * @memberof AppUserDto
     */
    'deletedAt': object | null;
}

