/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppUserDto } from './app-user-dto';

/**
 * 
 * @export
 * @interface AppUserList
 */
export interface AppUserList {
    /**
     * 
     * @type {number}
     * @memberof AppUserList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof AppUserList
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof AppUserList
     */
    'totalPages'?: number;
    /**
     * 
     * @type {Array<AppUserDto>}
     * @memberof AppUserList
     */
    'data'?: Array<AppUserDto>;
}

