/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAppUserDto
 */
export interface CreateAppUserDto {
    /**
     * The unique identifier for the user
     * @type {string}
     * @memberof CreateAppUserDto
     */
    'userIdentifier': string;
    /**
     * The UUID of the project
     * @type {string}
     * @memberof CreateAppUserDto
     */
    'projectId': string;
}

