/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateDataExportJobDto
 */
export interface CreateDataExportJobDto {
    /**
     * Filters to apply to the export
     * @type {object}
     * @memberof CreateDataExportJobDto
     */
    'filters': object;
    /**
     * Format of the export
     * @type {string}
     * @memberof CreateDataExportJobDto
     */
    'formatType': CreateDataExportJobDtoFormatTypeEnum;
}

export const CreateDataExportJobDtoFormatTypeEnum = {
    Json: 'JSON',
    Csv: 'CSV',
    Excel: 'EXCEL'
} as const;

export type CreateDataExportJobDtoFormatTypeEnum = typeof CreateDataExportJobDtoFormatTypeEnum[keyof typeof CreateDataExportJobDtoFormatTypeEnum];


