/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAuthTokenDto
 */
export interface CreateAuthTokenDto {
    /**
     * The ID of the project to generate an auth token for
     * @type {string}
     * @memberof CreateAuthTokenDto
     */
    'projectId': string;
    /**
     * The name of the auth token
     * @type {string}
     * @memberof CreateAuthTokenDto
     */
    'name': string;
}

