/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataExportJobDto } from './data-export-job-dto';

/**
 * 
 * @export
 * @interface DataExportJobResponseDto
 */
export interface DataExportJobResponseDto {
    /**
     * Data export job details
     * @type {DataExportJobDto}
     * @memberof DataExportJobResponseDto
     */
    'job': DataExportJobDto;
    /**
     * Success status of the operation
     * @type {boolean}
     * @memberof DataExportJobResponseDto
     */
    'success': boolean;
}

