/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataExportJobDto } from './data-export-job-dto';

/**
 * 
 * @export
 * @interface DataExportJobsResponseDto
 */
export interface DataExportJobsResponseDto {
    /**
     * Data export jobs
     * @type {Array<DataExportJobDto>}
     * @memberof DataExportJobsResponseDto
     */
    'jobs': Array<DataExportJobDto>;
    /**
     * Total count of jobs matching the filter criteria
     * @type {number}
     * @memberof DataExportJobsResponseDto
     */
    'total': number;
    /**
     * Success status of the operation
     * @type {boolean}
     * @memberof DataExportJobsResponseDto
     */
    'success': boolean;
}

