/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DebugSettingsDto
 */
export interface DebugSettingsDto {
    /**
     * Unique identifier for the debug settings
     * @type {string}
     * @memberof DebugSettingsDto
     */
    'id': string;
    /**
     * Project identifier
     * @type {string}
     * @memberof DebugSettingsDto
     */
    'projectId': string;
    /**
     * Log level for the project
     * @type {string}
     * @memberof DebugSettingsDto
     */
    'logLevel': DebugSettingsDtoLogLevelEnum;
    /**
     * Number of days to retain logs and metrics
     * @type {number}
     * @memberof DebugSettingsDto
     */
    'retentionDays': number;
    /**
     * Enable data diffing for changes
     * @type {boolean}
     * @memberof DebugSettingsDto
     */
    'enableDataDiffing': boolean;
    /**
     * Enable detailed logs
     * @type {boolean}
     * @memberof DebugSettingsDto
     */
    'enableDetailedLogs': boolean;
    /**
     * Enable metrics collection
     * @type {boolean}
     * @memberof DebugSettingsDto
     */
    'enableMetricsCollection': boolean;
    /**
     * Notify on error
     * @type {boolean}
     * @memberof DebugSettingsDto
     */
    'notifyOnError': boolean;
    /**
     * Notify on warning
     * @type {boolean}
     * @memberof DebugSettingsDto
     */
    'notifyOnWarning': boolean;
}

export const DebugSettingsDtoLogLevelEnum = {
    Info: 'INFO',
    Warning: 'WARNING',
    Error: 'ERROR',
    Debug: 'DEBUG'
} as const;

export type DebugSettingsDtoLogLevelEnum = typeof DebugSettingsDtoLogLevelEnum[keyof typeof DebugSettingsDtoLogLevelEnum];


