/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceDto
 */
export interface DeviceDto {
    /**
     * Device identifier
     * @type {string}
     * @memberof DeviceDto
     */
    'deviceId': string;
    /**
     * User identifier
     * @type {string}
     * @memberof DeviceDto
     */
    'userIdentifier': string;
    /**
     * Last time the device was seen
     * @type {string}
     * @memberof DeviceDto
     */
    'lastSeenAt'?: string;
    /**
     * Last time the device made a change
     * @type {string}
     * @memberof DeviceDto
     */
    'lastChangeAt'?: string;
    /**
     * When the device was created
     * @type {string}
     * @memberof DeviceDto
     */
    'createdAt': string;
    /**
     * When the device was deleted
     * @type {string}
     * @memberof DeviceDto
     */
    'deletedAt'?: string;
    /**
     * Device information
     * @type {object}
     * @memberof DeviceDto
     */
    'deviceInfo'?: object;
    /**
     * Last sync status
     * @type {string}
     * @memberof DeviceDto
     */
    'lastSyncStatus'?: DeviceDtoLastSyncStatusEnum;
}

export const DeviceDtoLastSyncStatusEnum = {
    Success: 'SUCCESS',
    Failed: 'FAILED',
    InProgress: 'IN_PROGRESS'
} as const;

export type DeviceDtoLastSyncStatusEnum = typeof DeviceDtoLastSyncStatusEnum[keyof typeof DeviceDtoLastSyncStatusEnum];


