/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeviceDto } from './device-dto';

/**
 * 
 * @export
 * @interface DeviceResponseDto
 */
export interface DeviceResponseDto {
    /**
     * Device details
     * @type {Array<DeviceDto>}
     * @memberof DeviceResponseDto
     */
    'devices': Array<DeviceDto>;
    /**
     * Total count of devices matching the filter criteria
     * @type {number}
     * @memberof DeviceResponseDto
     */
    'total': number;
    /**
     * Success status of the operation
     * @type {boolean}
     * @memberof DeviceResponseDto
     */
    'success': boolean;
}

