/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationSettingsDto
 */
export interface NotificationSettingsDto {
    /**
     * Whether marketing notifications are enabled
     * @type {boolean}
     * @memberof NotificationSettingsDto
     */
    'marketingEnabled': boolean;
    /**
     * Whether email notifications are enabled
     * @type {boolean}
     * @memberof NotificationSettingsDto
     */
    'emailEnabled': boolean;
}

