/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectResponseDto } from './project-response-dto';

/**
 * 
 * @export
 * @interface ProjectResponseList
 */
export interface ProjectResponseList {
    /**
     * 
     * @type {number}
     * @memberof ProjectResponseList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponseList
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponseList
     */
    'totalPages'?: number;
    /**
     * 
     * @type {Array<ProjectResponseDto>}
     * @memberof ProjectResponseList
     */
    'data'?: Array<ProjectResponseDto>;
}

