/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthTokenResponseDto } from './auth-token-response-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ProjectStatsResponseDto } from './project-stats-response-dto';

/**
 * 
 * @export
 * @interface ProjectResponseDto
 */
export interface ProjectResponseDto {
    /**
     * The unique identifier of the project
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'id': string;
    /**
     * The name of the project
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'name': string;
    /**
     * The ID of the user who owns this project
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'userId': string;
    /**
     * Number of app users in this project
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'appUsersCount': number;
    /**
     * When the project was created
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'createdAt': string;
    /**
     * When the project was last updated
     * @type {string}
     * @memberof ProjectResponseDto
     */
    'updatedAt': string;
    /**
     * When the project was deleted
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'userCount': number;
    /**
     * Number of active users today
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'activeUsersTodayCount': number;
    /**
     * Total number of devices registered in the project
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'deviceCount': number;
    /**
     * Total number of changes in the project
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'changesCount': number;
    /**
     * Number of changes pending synchronization
     * @type {number}
     * @memberof ProjectResponseDto
     */
    'pendingChangesCount': number;
    /**
     * Auth tokens for the project
     * @type {Array<AuthTokenResponseDto>}
     * @memberof ProjectResponseDto
     */
    'authTokens': Array<AuthTokenResponseDto>;
    /**
     * Project statistics including user counts, device counts, and change logs
     * @type {ProjectStatsResponseDto}
     * @memberof ProjectResponseDto
     */
    'stats': ProjectStatsResponseDto;
}

