/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectStatsResponseDto
 */
export interface ProjectStatsResponseDto {
    /**
     * Total number of users in the project
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'totalUsers': number;
    /**
     * Number of users active today
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'activeUsersToday': number;
    /**
     * Total number of devices registered in the project
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'totalDevices': number;
    /**
     * Number of devices currently online (seen in last 5 minutes)
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'onlineDevices': number;
    /**
     * Total number of changes in the project
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'totalChanges': number;
    /**
     * Sync success rate
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'syncSuccessRate': number;
    /**
     * Sync failure rate
     * @type {number}
     * @memberof ProjectStatsResponseDto
     */
    'syncFailureRate': number;
    /**
     * Last sync time
     * @type {string}
     * @memberof ProjectStatsResponseDto
     */
    'lastSync': string | null;
}

