/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReportConflictDto
 */
export interface ReportConflictDto {
    /**
     * Table name where the conflict occurred
     * @type {string}
     * @memberof ReportConflictDto
     */
    'tableName': string;
    /**
     * Record ID that has a conflict
     * @type {string}
     * @memberof ReportConflictDto
     */
    'recordId': string;
    /**
     * Client data that caused the conflict
     * @type {object}
     * @memberof ReportConflictDto
     */
    'clientData': object;
    /**
     * Server data that conflicts with client data
     * @type {object}
     * @memberof ReportConflictDto
     */
    'serverData': object;
    /**
     * Strategy used to resolve the conflict
     * @type {string}
     * @memberof ReportConflictDto
     */
    'resolutionStrategy': ReportConflictDtoResolutionStrategyEnum;
    /**
     * Data after conflict resolution
     * @type {object}
     * @memberof ReportConflictDto
     */
    'resolvedData': object;
    /**
     * Additional metadata for the conflict
     * @type {object}
     * @memberof ReportConflictDto
     */
    'metadata'?: object;
}

export const ReportConflictDtoResolutionStrategyEnum = {
    LastWriteWins: 'LAST_WRITE_WINS',
    ClientWins: 'CLIENT_WINS',
    ServerWins: 'SERVER_WINS',
    Custom: 'CUSTOM'
} as const;

export type ReportConflictDtoResolutionStrategyEnum = typeof ReportConflictDtoResolutionStrategyEnum[keyof typeof ReportConflictDtoResolutionStrategyEnum];


