/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * Password reset token received via email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}

