/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncChange } from './sync-change';

/**
 * 
 * @export
 * @interface SyncChangeBatchDto
 */
export interface SyncChangeBatchDto {
    /**
     * 
     * @type {Array<SyncChange>}
     * @memberof SyncChangeBatchDto
     */
    'changes': Array<SyncChange>;
    /**
     * 
     * @type {number}
     * @memberof SyncChangeBatchDto
     */
    'batch_timestamp': number;
    /**
     * 
     * @type {number}
     * @memberof SyncChangeBatchDto
     */
    'change_count': number;
}

