/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncChange
 */
export interface SyncChange {
    /**
     * 
     * @type {string}
     * @memberof SyncChange
     */
    'change_id': string;
    /**
     * 
     * @type {string}
     * @memberof SyncChange
     */
    'table_name': string;
    /**
     * 
     * @type {string}
     * @memberof SyncChange
     */
    'record_id': string;
    /**
     * 
     * @type {string}
     * @memberof SyncChange
     */
    'operation': SyncChangeOperationEnum;
    /**
     * Change data containing old/new values
     * @type {object}
     * @memberof SyncChange
     */
    'data': object;
    /**
     * 
     * @type {number}
     * @memberof SyncChange
     */
    'timestamp': number;
    /**
     * 
     * @type {number}
     * @memberof SyncChange
     */
    'version': number;
}

export const SyncChangeOperationEnum = {
    Insert: 'insert',
    Update: 'update',
    Delete: 'delete'
} as const;

export type SyncChangeOperationEnum = typeof SyncChangeOperationEnum[keyof typeof SyncChangeOperationEnum];


