/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncLogDto
 */
export interface SyncLogDto {
    /**
     * Unique identifier for the sync log
     * @type {string}
     * @memberof SyncLogDto
     */
    'id': string;
    /**
     * Project identifier
     * @type {string}
     * @memberof SyncLogDto
     */
    'projectId': string;
    /**
     * User identifier
     * @type {string}
     * @memberof SyncLogDto
     */
    'userIdentifier'?: string;
    /**
     * Device identifier
     * @type {string}
     * @memberof SyncLogDto
     */
    'deviceId'?: string;
    /**
     * Log message
     * @type {string}
     * @memberof SyncLogDto
     */
    'message': string;
    /**
     * Log level
     * @type {string}
     * @memberof SyncLogDto
     */
    'level': SyncLogDtoLevelEnum;
    /**
     * Timestamp of the log
     * @type {string}
     * @memberof SyncLogDto
     */
    'timestamp': string;
    /**
     * Additional metadata for the log
     * @type {object}
     * @memberof SyncLogDto
     */
    'metadata'?: object;
    /**
     * Associated sync session ID
     * @type {string}
     * @memberof SyncLogDto
     */
    'syncSessionId'?: string;
}

export const SyncLogDtoLevelEnum = {
    Info: 'INFO',
    Warning: 'WARNING',
    Error: 'ERROR',
    Debug: 'DEBUG'
} as const;

export type SyncLogDtoLevelEnum = typeof SyncLogDtoLevelEnum[keyof typeof SyncLogDtoLevelEnum];


