/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncActivityPeriod } from './sync-activity-period';

/**
 * 
 * @export
 * @interface SyncActivityDto
 */
export interface SyncActivityDto {
    /**
     * Sync activity for the last 24 hours
     * @type {SyncActivityPeriod}
     * @memberof SyncActivityDto
     */
    'last24h': SyncActivityPeriod;
    /**
     * Sync activity for the last 7 days
     * @type {SyncActivityPeriod}
     * @memberof SyncActivityDto
     */
    'last7d': SyncActivityPeriod;
    /**
     * Sync activity for the last 30 days
     * @type {SyncActivityPeriod}
     * @memberof SyncActivityDto
     */
    'last30d': SyncActivityPeriod;
    /**
     * Whether the operation was successful
     * @type {boolean}
     * @memberof SyncActivityDto
     */
    'success': boolean;
}

