/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncLogDto } from './sync-log-dto';

/**
 * 
 * @export
 * @interface SyncLogResponseDto
 */
export interface SyncLogResponseDto {
    /**
     * Sync log details
     * @type {Array<SyncLogDto>}
     * @memberof SyncLogResponseDto
     */
    'logs': Array<SyncLogDto>;
    /**
     * Total count of logs matching the filter criteria
     * @type {number}
     * @memberof SyncLogResponseDto
     */
    'total': number;
    /**
     * Success status of the operation
     * @type {boolean}
     * @memberof SyncLogResponseDto
     */
    'success': boolean;
}

