/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncSessionDto
 */
export interface SyncSessionDto {
    /**
     * Unique identifier for the sync session
     * @type {string}
     * @memberof SyncSessionDto
     */
    'id': string;
    /**
     * Device identifier
     * @type {string}
     * @memberof SyncSessionDto
     */
    'deviceId': string;
    /**
     * User identifier
     * @type {string}
     * @memberof SyncSessionDto
     */
    'userIdentifier': string;
    /**
     * Start time of the sync session
     * @type {string}
     * @memberof SyncSessionDto
     */
    'startTime': string;
    /**
     * End time of the sync session
     * @type {string}
     * @memberof SyncSessionDto
     */
    'endTime'?: string;
    /**
     * Status of the sync session
     * @type {string}
     * @memberof SyncSessionDto
     */
    'status': SyncSessionDtoStatusEnum;
    /**
     * Number of changes processed in this session
     * @type {number}
     * @memberof SyncSessionDto
     */
    'changesCount': number;
    /**
     * Duration of the sync session in milliseconds
     * @type {number}
     * @memberof SyncSessionDto
     */
    'syncDuration'?: number;
}

export const SyncSessionDtoStatusEnum = {
    Success: 'SUCCESS',
    Failed: 'FAILED',
    InProgress: 'IN_PROGRESS'
} as const;

export type SyncSessionDtoStatusEnum = typeof SyncSessionDtoStatusEnum[keyof typeof SyncSessionDtoStatusEnum];


