/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncActivityDataPoint } from './sync-activity-data-point';

/**
 * 
 * @export
 * @interface SyncActivityPeriod
 */
export interface SyncActivityPeriod {
    /**
     * Data points for the period
     * @type {Array<SyncActivityDataPoint>}
     * @memberof SyncActivityPeriod
     */
    'data': Array<SyncActivityDataPoint>;
    /**
     * Total number of sync operations in this period
     * @type {number}
     * @memberof SyncActivityPeriod
     */
    'total': number;
}

