/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner } from './sync-metrics-controller-get-aggregated-metrics200-response-data-inner';

/**
 * 
 * @export
 * @interface SyncMetricsControllerGetAggregatedMetrics200Response
 */
export interface SyncMetricsControllerGetAggregatedMetrics200Response {
    /**
     * 
     * @type {Array<SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner>}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200Response
     */
    'data'?: Array<SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200Response
     */
    'success'?: boolean;
}

