/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner
 */
export interface SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner
     */
    'timestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner
     */
    'average'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner
     */
    'min'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner
     */
    'max'?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncMetricsControllerGetAggregatedMetrics200ResponseDataInner
     */
    'count'?: number;
}

