/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncActivityDataPoint
 */
export interface SyncActivityDataPoint {
    /**
     * Timestamp for the data point
     * @type {string}
     * @memberof SyncActivityDataPoint
     */
    'timestamp': string;
    /**
     * Number of sync operations at this timestamp
     * @type {number}
     * @memberof SyncActivityDataPoint
     */
    'count': number;
}

