/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncMetricDto
 */
export interface SyncMetricDto {
    /**
     * Unique identifier for the sync metric
     * @type {string}
     * @memberof SyncMetricDto
     */
    'id': string;
    /**
     * Project identifier
     * @type {string}
     * @memberof SyncMetricDto
     */
    'projectId': string;
    /**
     * User identifier
     * @type {string}
     * @memberof SyncMetricDto
     */
    'userIdentifier'?: string;
    /**
     * Device identifier
     * @type {string}
     * @memberof SyncMetricDto
     */
    'deviceId'?: string;
    /**
     * Type of metric being recorded
     * @type {string}
     * @memberof SyncMetricDto
     */
    'metricType': string;
    /**
     * Value of the metric
     * @type {number}
     * @memberof SyncMetricDto
     */
    'value': number;
    /**
     * Timestamp when the metric was recorded
     * @type {string}
     * @memberof SyncMetricDto
     */
    'timestamp': string;
    /**
     * Additional metadata for the metric
     * @type {object}
     * @memberof SyncMetricDto
     */
    'metadata'?: object;
}

