/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TableChangeCountDto
 */
export interface TableChangeCountDto {
    /**
     * Number of CREATE operations
     * @type {number}
     * @memberof TableChangeCountDto
     */
    'creates': number;
    /**
     * Number of UPDATE operations
     * @type {number}
     * @memberof TableChangeCountDto
     */
    'updates': number;
    /**
     * Number of DELETE operations
     * @type {number}
     * @memberof TableChangeCountDto
     */
    'deletes': number;
    /**
     * Total number of changes
     * @type {number}
     * @memberof TableChangeCountDto
     */
    'total': number;
}

