/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TableChangeCountDto } from './table-change-count-dto';

/**
 * 
 * @export
 * @interface TableChangesSummaryDto
 */
export interface TableChangesSummaryDto {
    /**
     * Table name
     * @type {string}
     * @memberof TableChangesSummaryDto
     */
    'tableName': string;
    /**
     * 
     * @type {TableChangeCountDto}
     * @memberof TableChangesSummaryDto
     */
    'counts': TableChangeCountDto;
}

