/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TableChangesSummaryDto } from './table-changes-summary-dto';

/**
 * 
 * @export
 * @interface TableChangesSummaryResponseDto
 */
export interface TableChangesSummaryResponseDto {
    /**
     * 
     * @type {Array<TableChangesSummaryDto>}
     * @memberof TableChangesSummaryResponseDto
     */
    'tables': Array<TableChangesSummaryDto>;
}

