/* tslint:disable */
/* eslint-disable */
/**
 * PocketSync API
 * API documentation for PocketSync backend services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * Unique identifier of the user
     * @type {string}
     * @memberof UserResponseDto
     */
    'id': string;
    /**
     * User email address
     * @type {string}
     * @memberof UserResponseDto
     */
    'email': string;
    /**
     * User first name
     * @type {object}
     * @memberof UserResponseDto
     */
    'firstName': object | null;
    /**
     * User last name
     * @type {object}
     * @memberof UserResponseDto
     */
    'lastName': object | null;
    /**
     * URL of the user\'s avatar
     * @type {object}
     * @memberof UserResponseDto
     */
    'avatarUrl'?: object;
    /**
     * Whether the user\'s email is verified
     * @type {boolean}
     * @memberof UserResponseDto
     */
    'isEmailVerified': boolean;
    /**
     * Timestamp of when the user was created
     * @type {string}
     * @memberof UserResponseDto
     */
    'createdAt': string;
    /**
     * Timestamp of when the user was last updated
     * @type {string}
     * @memberof UserResponseDto
     */
    'updatedAt': string;
}

